version: "3"

services:
    db:
        image: mongo
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ${LOCAL_DATA_DIR}:/data
        entrypoint: mongod --config /etc/mongodb-conf.yaml

